# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
	before_all do
		setup_ci(provider: "travis")
	end

	lane :build_ipa do
		skip_docs
		match(
			type: "adhoc",
			app_identifier: "tech.takenoko.ios.flutter-architecture",
			git_basic_authorization: Base64.strict_encode64(ENV["GITHUB_ACTOR"] + ":" + ENV["MATCH_GIT_BASIC_AUTHORIZATION"]),
			readonly: true
		)
		build_app(
			scheme: "Runner",
			export_method: "ad-hoc",
			output_directory: "../build/ios",
			output_name: "app-release.ipa"
		)    
	end

	after_all do |lane|
	end
	
	error do |lane, exception|
	end
end
